version: '3.9'
services:
  mysql:
    image: postgres:13
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "5432:5432"

  php-fpm:
    image: webdevops/php:7.3
    hostname: php-fpm
    volumes:
      - "./:/app"
    working_dir: "/app"
    depends_on:
      - mysql

  nginx:
    image: webdevops/nginx
    hostname: nginx
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      WEB_DOCUMENT_INDEX: index.php
      WEB_PHP_SOCKET: php-fpm:9000
    ports:
      - "80:80"
    volumes:
      - "./:/app"
    depends_on:
      - php-fpm
